[package]
name = "opengl"
version = "0.1.0"
authors = ["David A Burns <davidaaronbburns@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = "0.17.0"
gl = "0.12.0"
glfw = "0.26.1"
image = "0.21.0"
tobj = "0.1.6"
num = "0.2.0"
rand = "0.6.5"
